"""Add summary column to conversations

Revision ID: 11b9c8a8a322
Revises: 
Create Date: 2025-01-13 09:30:30.856613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b9c8a8a322'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('model_configs', sa.Column('model_type', sa.String(), nullable=True))
    op.drop_column('model_configs', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_configs', sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('model_configs', 'model_type')
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
