"""add password_hash and formalize user_id

Revision ID: 874a09cc4bae
Revises: 11b9c8a8a322
Create Date: 2026-01-01 13:49:58.693809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874a09cc4bae'
down_revision: Union[str, None] = '11b9c8a8a322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
